In [6]:
import sys
import sklearn
import tensorflow as tf
import pandas as pd
from tensorflow import keras
import numpy as np
import os

df_2023 = pd.read_csv('g2f_2023_phenotypic_clean_data.csv', encoding='latin-1')
df_2022 = pd.read_csv('g2f_2022_phenotypic_clean_data.csv', encoding='latin-1')
df_2021 = pd.read_csv('g2f_2021_phenotypic_clean_data.csv', encoding='latin-1')
df_2020 = pd.read_csv('g2f_2020_phenotypic_clean_data.csv', encoding='latin-1')
df_2019 = pd.read_csv('g2f_2019_phenotypic_clean_data.csv', encoding='latin-1')

/var/folders/zw/qttxqty93qq2w6vtn3d1nwg80000gn/T/ipykernel_67354/2228034013.py:9: DtypeWarning: Columns (0: Plot, 1: Pass) have mixed types. Specify dtype option on import or set low_memory=False.
  df_2023 = pd.read_csv('g2f_2023_phenotypic_clean_data.csv', encoding='latin-1')
/var/folders/zw/qttxqty93qq2w6vtn3d1nwg80000gn/T/ipykernel_67354/2228034013.py:11: DtypeWarning: Columns (0: Plot) have mixed types. Specify dtype option on import or set low_memory=False.
  df_2021 = pd.read_csv('g2f_2021_phenotypic_clean_data.csv', encoding='latin-1')
/var/folders/zw/qttxqty93qq2w6vtn3d1nwg80000gn/T/ipykernel_67354/2228034013.py:12: DtypeWarning: Columns (0: Pass, 1: Filler) have mixed types. Specify dtype option on import or set low_memory=False.
  df_2020 = pd.read_csv('g2f_2020_phenotypic_clean_data.csv', encoding='latin-1')
/var/folders/zw/qttxqty93qq2w6vtn3d1nwg80000gn/T/ipykernel_67354/2228034013.py:13: DtypeWarning: Columns (0: Filler [enter 'filler' or blank], 1: Possible subs, 2: Confirmed subs) have mixed types. Specify dtype option on import or set low_memory=False.
  df_2019 = pd.read_csv('g2f_2019_phenotypic_clean_data.csv', encoding='latin-1')

In [10]:
import pandas as pd

files = [
    'g2f_2023_phenotypic_clean_data.csv',
    'g2f_2022_phenotypic_clean_data.csv',
    'g2f_2021_phenotypic_clean_data.csv',
    'g2f_2020_phenotypic_clean_data.csv',
    'g2f_2019_phenotypic_clean_data.csv'
]

# columns to keep and rename
cols = {
    "Year": "year",
    "Pedigree": "pedigree",
    "Field-Location": "location",
    "Plot area (ft2)": "area",
    "Plot": "plot",
    "Plant Height [cm]": "plant_height",
    "Ear Height [cm]": "ear_height",
    "Anthesis [MM/DD/YY]": "anthesis_date",
    "Date Plot Planted [MM/DD/YY]": "plant_date",
    "Date Plot Harvested [MM/DD/YY]": "harvest_date",
    "Grain Yield (bu/A)": "grain_yield"
}

dfs = []

for f in files:
    df = pd.read_csv(f, encoding='latin-1')

    # keep only desired columns
    df = df[list(cols.keys())]

    # rename columns
    df = df.rename(columns=cols)

    # convert dates to datetime
    date_cols = ["plant_date", "harvest_date", "anthesis_date"]
    for c in date_cols:
        df[c] = pd.to_datetime(df[c], errors='coerce')

    dfs.append(df)

# combine all years
df_all = pd.concat(dfs, ignore_index=True)
df_all = df_all.dropna(subset=["ear_height", "plant_height"])

# optional cleaning
df_all = df_all.drop_duplicates()
df_all = df_all.dropna(subset=["grain_yield"])

print(df_all.head())

# save cleaned dataset
df_all.to_csv("g2f_cleaned.csv", index=False)

/var/folders/1s/kv1k50_n0sl11vwn99v6zfc00000gn/T/ipykernel_54076/4147291343.py:29: DtypeWarning: Columns (0: Plot, 1: Pass) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(f, encoding='latin-1')
/var/folders/1s/kv1k50_n0sl11vwn99v6zfc00000gn/T/ipykernel_54076/4147291343.py:29: DtypeWarning: Columns (0: Plot) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(f, encoding='latin-1')
/var/folders/1s/kv1k50_n0sl11vwn99v6zfc00000gn/T/ipykernel_54076/4147291343.py:29: DtypeWarning: Columns (0: Pass, 1: Filler) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(f, encoding='latin-1')
/var/folders/1s/kv1k50_n0sl11vwn99v6zfc00000gn/T/ipykernel_54076/4147291343.py:40: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  df[c] = pd.to_datetime(df[c], errors='coerce')
/var/folders/1s/kv1k50_n0sl11vwn99v6zfc00000gn/T/ipykernel_54076/4147291343.py:40: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  df[c] = pd.to_datetime(df[c], errors='coerce')
/var/folders/1s/kv1k50_n0sl11vwn99v6zfc00000gn/T/ipykernel_54076/4147291343.py:40: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  df[c] = pd.to_datetime(df[c], errors='coerce')
/var/folders/1s/kv1k50_n0sl11vwn99v6zfc00000gn/T/ipykernel_54076/4147291343.py:29: DtypeWarning: Columns (0: Filler [enter 'filler' or blank], 1: Possible subs, 2: Confirmed subs) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(f, encoding='latin-1')
/var/folders/1s/kv1k50_n0sl11vwn99v6zfc00000gn/T/ipykernel_54076/4147291343.py:40: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  df[c] = pd.to_datetime(df[c], errors='coerce')
/var/folders/1s/kv1k50_n0sl11vwn99v6zfc00000gn/T/ipykernel_54076/4147291343.py:40: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  df[c] = pd.to_datetime(df[c], errors='coerce')
/var/folders/1s/kv1k50_n0sl11vwn99v6zfc00000gn/T/ipykernel_54076/4147291343.py:40: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  df[c] = pd.to_datetime(df[c], errors='coerce')

     year                    pedigree location  area  plot  plant_height  \
176  2023  GEMN-0097_PHN46_0005/LH244     DEH1  75.0  1339         282.0
177  2023             GEMN-0177/LH244     DEH1  75.0  1340         283.0
178  2023       MO44_PHG47_0125/LH244     DEH1  75.0  1341         254.0
179  2023           W10010_0032/LH244     DEH1  75.0  1342         252.0
180  2023           W10001_0030/LH244     DEH1  75.0  1343         252.0

     ear_height anthesis_date plant_date harvest_date  grain_yield
176       139.0    2023-07-13 2023-05-08   2023-09-21   292.386405
177       155.0    2023-07-16 2023-05-08   2023-09-21   197.613763
178       123.0    2023-07-12 2023-05-08   2023-09-21   154.403446
179       116.0    2023-07-12 2023-05-08   2023-09-21   177.538973
180       121.0    2023-07-11 2023-05-08   2023-09-21    45.842942

In [12]:
df_all

,year,pedigree,location,area,plot,plant_height,ear_height,anthesis_date,plant_date,harvest_date,grain_yield
176,2023,GEMN-0097_PHN46_0005/LH244,DEH1,75.0,1339,282.000000,139.000000,2023-07-13,2023-05-08,2023-09-21,292.386405
177,2023,GEMN-0177/LH244,DEH1,75.0,1340,283.000000,155.000000,2023-07-16,2023-05-08,2023-09-21,197.613763
178,2023,MO44_PHG47_0125/LH244,DEH1,75.0,1341,254.000000,123.000000,2023-07-12,2023-05-08,2023-09-21,154.403446
179,2023,W10010_0032/LH244,DEH1,75.0,1342,252.000000,116.000000,2023-07-12,2023-05-08,2023-09-21,177.538973
180,2023,W10001_0030/LH244,DEH1,75.0,1343,252.000000,121.000000,2023-07-11,2023-05-08,2023-09-21,45.842942
...,...,...,...,...,...,...,...,...,...,...,...
99232,2019,PHW65_MOG_0173/PHT69,WIH2,100.0,1595,266.666667,143.333333,2019-08-14,2019-06-03,2019-11-20,128.806515
99233,2019,PHW65_MOG_0087/PHT69,WIH2,100.0,1596,250.000000,140.000000,2019-08-12,2019-06-03,2019-11-20,127.453780
99234,2019,PHW65_MOG_0170/PHT69,WIH2,100.0,1597,261.666667,133.333333,2019-08-13,2019-06-03,2019-11-20,69.083840
99235,2019,PHW65_MOG_0200/PHT69,WIH2,100.0,1598,270.000000,141.666667,2019-08-10,2019-06-03,2019-11-20,115.618108
99237,2019,PHW65_MOG_0287/PHT69,WIH2,100.0,1600,250.000000,120.000000,2019-08-11,2019-06-03,2019-11-20,169.891917

In [13]:
mi_df = df_all[df_all["location"].str.contains("MI", na=False)]

most_common_mi_location = mi_df["location"].value_counts().idxmax()

print("Most common MI location:", most_common_mi_location)

df_mi_location = df_all[df_all["location"] == most_common_mi_location]

Most common MI location: MIH1

In [14]:
df_mi_location

,year,pedigree,location,area,plot,plant_height,ear_height,anthesis_date,plant_date,harvest_date,grain_yield
8494,2023,GEMN-0192_PHK76_0041/LH244,MIH1,110.0,939,226.5,90.0,2023-08-05,2023-05-24,2023-11-15,117.617021
8495,2023,BGEM-0039-N/LH244,MIH1,110.0,940,250.5,123.0,2023-08-06,2023-05-24,2023-11-15,183.334945
8496,2023,GEMN-0192_PHK76_0007/LH244,MIH1,110.0,941,208.5,86.5,2023-07-30,2023-05-24,2023-11-15,147.271831
8497,2023,MO17_PHW30-200-(2N)-02/LH244,MIH1,110.0,942,237.5,118.5,2023-08-05,2023-05-24,2023-11-15,186.112050
8498,2023,GEMN-0096_PHN46_0012/LH244,MIH1,110.0,943,242.0,110.5,2023-08-05,2023-05-24,2023-11-15,165.331339
...,...,...,...,...,...,...,...,...,...,...,...
86585,2019,PHN11/PHT69,MIH1,95.0,496,211.0,116.0,2019-07-28,2019-05-27,2019-11-17,181.262759
86586,2019,PHN11_PHW65_0358/PHT69,MIH1,95.0,497,188.5,105.0,2019-07-30,2019-05-27,2019-11-17,141.583566
86587,2019,PHN11_PHW65_0275/PHT69,MIH1,95.0,498,205.5,105.5,2019-07-30,2019-05-27,2019-11-17,185.609553
86588,2019,PHN11_PHW65_0423/PHT69,MIH1,95.0,499,214.5,114.0,2019-07-30,2019-05-27,2019-11-17,170.099697
86589,2019,PHN11_PHW65_0279/PHT69,MIH1,95.0,500,171.0,82.0,2019-08-01,2019-05-27,2019-11-17,156.403598